#通用配置
#默认环境
spring:
  profiles:
    active: dev
  application:
    name: space-gateway


#zuul配置
zuul:
  host:
    #zuul的超时配置要大于ribbon
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    space-consumer:
      path: /consumer/**
      serviceId: space-consumer
      stripPrefix: false
    space-usercenter:
      path: /usercenter/**
      serviceId: space-usercenter
      stripPrefix: false
    space-console:
      path: /console/**
      serviceId: space-console
      stripPrefix: false

#ribbon超时配置
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000