#开发环境配置
server:
  port: 8081


#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eurekaServer/eureka

#rabbit mq
spring:
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: admin
    password: kgdiyniqmq
    virtual-host: space_vhost